// <auto-generated />
using LunchAndLearn_AIIntegration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LunchAndLearn_AIIntegration.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20260227053702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("LunchAndLearn_AIIntegration.Data.Models.AIConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AI");
                });

            modelBuilder.Entity("LunchAndLearn_AIIntegration.Data.Models.AIConfigurationContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AIContext");
                });

            modelBuilder.Entity("LunchAndLearn_AIIntegration.Data.Models.AI_KoboldAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assessment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoboldId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AI_KoboldAssessments");
                });

            modelBuilder.Entity("LunchAndLearn_AIIntegration.Data.Models.Kobold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kobolds");
                });
#pragma warning restore 612, 618
        }
    }
}
